# -*- coding: utf-8 -*-
"""logo_recognition_clustring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Mahmood-Anaam/logo-similarity-retrieval/blob/main/notebooks/logo_recognition_clustring.ipynb

# Logo Recognition Clustring

This project aims to address the challenge of logo recognition and similarity search in the context of limited available datasets. Due to the vast diversity of logos and the constant emergence of new designs, traditional logo recognition systems often struggle to maintain high accuracy and robustness. To tackle this issue, the project proposes the use of synthetic data generation techniques alongside advanced deep learning models to significantly improve the system's ability to accurately identify and find similar logos.

## Imports
"""

# This get the RAPIDS-Colab install files and test check your GPU.  Run this and the next cell only.
# Please read the output of this cell.  If your Colab Instance is not RAPIDS compatible, it will warn you and give you remediation steps.
!git clone https://github.com/rapidsai/rapidsai-csp-utils.git
!python rapidsai-csp-utils/colab/pip-install.py

import cudf
import cuml
import cupy as cp
from cuml.common.device_selection import using_device_type, set_global_device_type


(
    cudf.__version__,
    cuml.__version__,
    cp.__version__

 )

!pip install datasets -q

import os
import numpy as np
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
import torch
import datasets
import warnings
warnings.filterwarnings('ignore')


output_dir = f"/content/drive/MyDrive/logo_recognition_similarity_search_project/output"
os.makedirs(output_dir,exist_ok=True)
ds_dir = f"{output_dir}/logo-recognition-embeddings"

"""## Load Dataset"""

ds = datasets.load_from_disk(ds_dir)
ds = ds.with_format("numpy")
ds

ds.features

# Extract image and text embeddings
image_embeddings = np.array(ds['image_embedding'])
prompt_embeddings = np.array(ds['prompt_embedding'])

# Concatenate image and text embeddings
combined_embeddings = np.hstack((image_embeddings, prompt_embeddings))

del image_embeddings
del prompt_embeddings

combined_embeddings.shape

"""## Clustring

### UMAP

This section applies **UMAP** (Uniform Manifold Approximation and Projection) to the combined image and text embeddings. **UMAP** is a dimensionality reduction technique well-suited for visualizing high-dimensional data while preserving the underlying data structure.  The reduced embeddings are then used for clustering.  The code in this section assumes the existence of a preprocessed dataset with combined embeddings as generated in earlier parts of the notebooks.
"""

n_components=600

from cuml.manifold import UMAP

umap_model = UMAP(
                  n_components=n_components,
                  metric='cosine',
                  min_dist=0.0,
                  random_state=42,
                  )

reduced_embeddings = umap_model.fit_transform(combined_embeddings)

reduced_embeddings.shape

np.save(f"{output_dir}/reduced_{n_components}_embeddings.npy", reduced_embeddings)

reduced_embeddings = np.load(f"{output_dir}/reduced_{n_components}_embeddings.npy")
reduced_embeddings.shape

"""### HDBSCAN

**HDBSCAN** (Hierarchical Density-Based Spatial Clustering of Applications with Noise) is a clustering algorithm that is well-suited for data with varying densities.  Unlike K-Means, which assumes spherical clusters of equal density, HDBSCAN can identify clusters of arbitrary shapes and sizes.  It's particularly effective at finding clusters in noisy data and identifying outliers.  We will use HDBSCAN to cluster the reduced embeddings.

"""

from cuml.cluster.hdbscan import HDBSCAN

# A higher min_cluster_size will generate fewer clusters.
# A lower min_cluster_size will generate more clusters.

hdbscan_model = HDBSCAN(min_cluster_size=2,
                        cluster_selection_epsilon=0.005,
                        metric='euclidean',
                        cluster_selection_method='eom',
                        prediction_data=True,

                        )

hdbscan_model.fit(reduced_embeddings)

hdbscan_model.labels_.shape

hdbscan_model.n_clusters_

unique_labels, counts = np.unique(hdbscan_model.labels_, return_counts=True)
print(f"Number of unique labels: {len(unique_labels)}")
label_counts_df = pd.DataFrame({'Label': unique_labels, 'Count': counts})
label_counts_df

label_counts_df.describe()

label_counts_df[label_counts_df['Count'] == 1].shape

np.save(f"{output_dir}/hdbscan_{n_components}_labels.npy", hdbscan_model.labels_)

from joblib import dump

dump(hdbscan_model, f"{output_dir}/hdbscan_{n_components}_model.joblib")

from joblib import load

hdbscan_model = load(f"{output_dir}/hdbscan_{n_components}_model.joblib")
hdbscan_model.labels_.shape

"""---

### Outliers
"""

outlier_indices = np.where(hdbscan_model.labels_ == -1)[0]
reduced_embeddings_outliers = reduced_embeddings[outlier_indices]
reduced_embeddings_outliers.shape

from cuml.cluster.hdbscan import HDBSCAN

# A higher min_cluster_size will generate fewer clusters.
# A lower min_cluster_size will generate more clusters.

hdbscan_outliers_model = HDBSCAN(min_cluster_size=2,
                                cluster_selection_epsilon=0.005,
                                metric='euclidean',
                                cluster_selection_method='eom',
                                prediction_data=True,
                                )

hdbscan_outliers_model.fit(reduced_embeddings_outliers)

hdbscan_outliers_model.n_clusters_

unique_outlier_labels, outlier_counts = np.unique(hdbscan_outliers_model.labels_, return_counts=True)
print(f"Number of unique labels: {len(unique_outlier_labels)}")
outlier_label_counts_df = pd.DataFrame({'Label': unique_outlier_labels, 'Count': outlier_counts})
outlier_label_counts_df

outlier_label_counts_df.describe()

soft_clusters = cuml.cluster.hdbscan.membership_vector(hdbscan_outliers_model, reduced_embeddings_outliers[hdbscan_outliers_model.labels_ == -1])
soft_clusters.shape

argmax_propability = np.argmax(soft_clusters, axis=1)
argmax_propability

outliers_labels = hdbscan_outliers_model.labels_
outliers_labels[outliers_labels ==-1] = argmax_propability
outliers_labels.shape

unique_outlier_labels, outlier_counts = np.unique(outliers_labels, return_counts=True)
print(f"Number of unique labels: {len(unique_outlier_labels)}")
outlier_label_counts_df = pd.DataFrame({'Label': unique_outlier_labels, 'Count': outlier_counts})
outlier_label_counts_df

outlier_label_counts_df.describe()

np.save(f"{output_dir}/hdbscan_{n_components}_outliers_labels.npy", outliers_labels)

from joblib import dump

dump(hdbscan_outliers_model, f"{output_dir}/hdbscan_{n_components}_outliers_model.joblib")

from joblib import load

hdbscan_outliers_model = load(f"{output_dir}/hdbscan_{n_components}_outliers_model.joblib")
hdbscan_outliers_model.labels_.shape

"""

---

"""

outliers_labels.shape

hdbscan_outliers_model.n_clusters_,hdbscan_model.n_clusters_

outlier_label_counts_df

outliers_labels.shape

outliers_labels = outliers_labels+hdbscan_model.n_clusters_+1
outliers_labels.min(),outliers_labels.max()

fainl_labels = hdbscan_model.labels_
fainl_outlier_indices = np.where(hdbscan_model.labels_ == -1)[0]

fainl_labels[fainl_outlier_indices] = outliers_labels
fainl_labels.shape,fainl_labels.min(),fainl_labels.max()

unique_labels, counts = np.unique(fainl_labels, return_counts=True)
print(f"Number of unique labels: {len(unique_labels)}")
label_counts_df = pd.DataFrame({'Label': unique_labels, 'Count': counts})
label_counts_df

label_counts_df.describe()

np.save(f"{output_dir}/hdbscan_{n_components}_fainl_labels.npy", fainl_labels)

"""## Save

This section saves the clustering results to google drive.  These files will be used in subsequent notebooks for analysis and visualization.  The soft clusters represent the probability of each data point belonging to each cluster, providing a measure of uncertainty in the cluster assignments.
"""

ds = ds.add_column('category', fainl_labels.tolist())

ds

ds.features

df = ds.remove_columns(['image_embedding', 'prompt_embedding']).to_pandas()
df.head()

df.shape

df.to_csv(f"{output_dir}/logo-recognition-with-{n_components}-hdbscan-category.tsv", sep='\t', index=False)

df = pd.read_csv(f"{output_dir}/logo-recognition-with-{n_components}-hdbscan-category.tsv", sep='\t')
df.head()

"""

---

"""