# -*- coding: utf-8 -*-
"""Methodology.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Mahmood-Anaam/logo-similarity-retrieval/blob/main/notebooks/Methodology.ipynb

## **Methodology**

### **Pre-processing Stage**

The pre-processing stage constitutes the backbone of the proposed logo recognition and similarity retrieval pipeline. It is designed to transform raw multimodal inputs—synthetic logo images and their associated textual prompts—into structured, low-dimensional representations suitable for unsupervised clustering and deep metric learning. This stage ensures that both visual semantics and textual concepts are jointly modeled in a way that enables scalable training and retrieval.

Given the constraints of real-world logo datasets, including limited variability, labeling costs, and poor generalizability to unseen brand identities, this research employs a synthetically generated dataset comprising **1,777,584 logo images**, each accompanied by a **prompt** describing the logo’s visual style, theme, or concept. To leverage this rich dual-modality, we construct **multimodal embeddings** as follows:

Each image is processed using a frozen **ResNet50** model pretrained on ImageNet. The final fully connected classification layer is removed, and the output from the last convolutional block is flattened to obtain a **2048-dimensional** visual embedding. Simultaneously, the corresponding prompt text is embedded using the transformer-based **MiniLM model** (`all-MiniLM-L6-v2`), producing a **384-dimensional** semantic embedding that captures linguistic features relevant to logo design.

The visual and textual embeddings are then **concatenated** to yield a unified **2432-dimensional feature vector** for each logo. While this combined representation is expressive, its high dimensionality poses challenges for clustering due to the curse of dimensionality and computational overhead. To mitigate this, we apply **UMAP (Uniform Manifold Approximation and Projection)** for nonlinear dimensionality reduction, projecting the embeddings into a **600-dimensional space**. UMAP is configured with cosine similarity as the distance metric and a minimum distance of zero to preserve fine-grained local structure in the embedding space.

Following dimensionality reduction, the dataset is subjected to **unsupervised clustering using HDBSCAN**, a hierarchical density-based clustering algorithm that does not require a predefined number of clusters. HDBSCAN identifies dense regions in the embedding space as clusters and marks low-density points as outliers (with label = -1). To ensure that all logos are eventually assigned to a category, we perform **a second clustering pass** specifically on the outlier samples using a new HDBSCAN model. The cluster IDs from this secondary pass are offset to prevent overlap with those from the primary clustering phase.

The result of this two-step clustering pipeline is a set of **209,310 distinct visual categories**, each containing at least two images. These categories serve as **weak labels** that guide the construction of triplets in the subsequent metric learning stage. This form of pseudo-labeling ensures that the model can learn similarity relationships without relying on manually annotated classes, allowing the system to scale across millions of logos with minimal supervision.

Once clustering is complete, the dataset is **partitioned into training and test subsets** using a stratified strategy that preserves category integrity. For each visual category produced by HDBSCAN, all associated samples are considered. If the category contains fewer than two images, it is excluded from training to avoid degenerate triplets. For the remaining categories, the samples are randomly shuffled, and approximately 80% are allocated to the training set, while up to 20% are reserved for testing—provided that at least two samples remain in the training portion to allow valid anchor–positive pairs. This procedure ensures that every triplet sampled during training reflects meaningful intra-class and inter-class relationships.

The final result of the pre-processing stage is a clean, structured, and semantically consistent dataset consisting of **1,458,113 training samples** and **319,471 test samples**, each labeled by a pseudo-category derived from unsupervised clustering. This foundation enables high-quality metric learning in the training stage and facilitates robust performance evaluation on previously unseen logos.

### **Training Stage**

The training stage represents the critical phase in which the proposed model learns to encode visual and semantic similarities between logos within a structured, discriminative embedding space. This embedding space must ensure that logos sharing similar visual styles and semantic attributes are located in close proximity, while dissimilar logos are projected further apart. To achieve this, the system adopts a metric learning strategy built upon a Triplet Network trained using the Triplet Margin Loss. This approach not only facilitates robust similarity retrieval but also supports generalization to unseen logos—an essential requirement given the open-ended nature of real-world logo design.

At the heart of the model lies a Triplet Network architecture that takes as input three logo samples: an anchor, a positive sample that is semantically and visually similar to the anchor, and a negative sample that is distinct. Each of these three inputs is processed through a shared neural embedding function, ensuring consistent representation and learning behavior. The output is a compact, normalized vector representation for each logo, which is optimized such that the distance between the anchor and positive is minimized, while the distance between the anchor and negative is maximized by a predefined margin.

The embedding function itself is composed of two main components. First, a frozen ResNet50 backbone acts as a feature extractor, transforming the input image into a 2048-dimensional visual representation. This backbone is not fine-tuned during training to preserve the generalization capacity of pretrained visual features. Second, a projection head is applied to reduce the dimensionality of the visual embedding and map it into a compact, trainable metric space. This head is implemented as a two-layer feedforward neural network with ReLU nonlinearity followed by L2 normalization. Formally, the embedding function $f(x)$ can be expressed as:

$$
f(x) = \frac{W_2 \cdot \text{ReLU}(W_1 \cdot x + b_1) + b_2}{\left\| W_2 \cdot \text{ReLU}(W_1 \cdot x + b_1) + b_2 \right\|_2}
$$

where $W_1 \in \mathbb{R}^{512 \times 2048}$, $W_2 \in \mathbb{R}^{256 \times 512}$, and the final output is a unit-normalized vector in $\mathbb{R}^{256}$. This projection ensures that the model outputs reside on a hypersphere, allowing the Euclidean (L2) distance to serve as a meaningful similarity metric.

The model is optimized using the standard **Triplet Margin Loss**, which encourages the anchor-positive distance to be smaller than the anchor-negative distance by a fixed margin $\alpha$. The objective function for a single triplet $(x_a, x_p, x_n)$ is defined as:

$$
\mathcal{L}(x_a, x_p, x_n) = \max\left(0, \, \|f(x_a) - f(x_p)\|_2^2 - \|f(x_a) - f(x_n)\|_2^2 + \alpha \right)
$$

In this work, the margin parameter $\alpha$ is set to 1.0, which was found to be sufficient to enforce meaningful separation between dissimilar samples without compromising training stability. The choice of L2 distance reflects the geometric intuition behind the embedding space, where similar items should cluster and form dense neighborhoods.

Training data is composed of triplets constructed dynamically from the clustered dataset. For each anchor logo, a positive sample is selected from the same cluster (category) but must differ from the anchor to avoid trivial cases. A negative sample is then chosen from a different cluster, ensuring semantic and visual dissimilarity. This dynamic sampling strategy, applied per mini-batch, enhances training diversity and avoids redundancy. The categories used in sampling are those generated via unsupervised HDBSCAN clustering in the previous phase, which ensures that the model is trained on naturally discovered groups of visually similar logos.

The training process is conducted over 50 epochs using the Adam optimizer, with an initial learning rate of $1 \times 10^{-4}$, decayed periodically via a step scheduler to improve convergence. Each training batch contains 1024 triplets, totaling 3072 logo images per iteration (anchor, positive, and negative). Training is performed using mixed precision to reduce memory consumption and accelerate computation, and loss values are monitored across epochs to track learning progress.

Results from training indicate that the model converges rapidly. The triplet loss exhibits a steep decline within the first few epochs, plateauing by epoch 5, suggesting that the network quickly adapts to the metric structure imposed by the clustering. This early convergence behavior is expected, given the strong semantic signal provided by the synthetic dataset and the robustness of ResNet50 features.

The final trained model is capable of producing discriminative 256-dimensional embeddings for any input logo image. These embeddings are used in subsequent stages for both retrieval and evaluation. Importantly, because the model learns similarity in a weakly supervised manner, it generalizes well to logos outside the training distribution—a property that is essential for deployment in real-world scenarios where new logo styles and brands appear continuously.



### **Retrieval Pipeline**

The retrieval pipeline represents the operational phase of the proposed logo recognition system, where the trained model is utilized to perform similarity-based logo search in real-time. This stage capitalizes on the embedding space learned through metric learning to identify logos that are semantically and visually similar to a given query. It transforms the learned representations from a theoretical construct into a functional retrieval mechanism capable of handling large-scale logo datasets.

At the core of the retrieval pipeline lies the 256-dimensional output of the TripletNet model. Once trained, this model is employed to extract embeddings for all logo images in both the training and test sets. Each embedding is a unit-normalized vector that encodes rich information about the structure, color, shape, and style of the logo, as well as latent semantic cues inferred from the associated prompt. These embeddings are computed in batch mode and stored efficiently using the Hugging Face `datasets` library to enable fast and reproducible access.

To enable scalable similarity search, a **FAISS (Facebook AI Similarity Search)** index is constructed over the training set embeddings. FAISS is a highly optimized library for efficient nearest neighbor search in high-dimensional spaces, particularly suited for large datasets. In this work, a **flat L2 index** is used, which performs brute-force search but benefits significantly from GPU acceleration and vectorized operations due to the relatively moderate dimensionality of the embeddings. This choice prioritizes retrieval accuracy over approximate speed-ups that could result in degraded performance.

When a user provides a query logo—either as a raw image or as a precomputed embedding—the system processes it through the trained TripletNet to generate its 256-dimensional embedding. This embedding is then used to perform a **Top-K similarity search** against the indexed training embeddings using L2 distance as the similarity metric. The FAISS engine returns the indices and similarity scores of the K nearest neighbors. These scores reflect the closeness of the query to each retrieved logo in the learned metric space.

The retrieval results are not only used for quantitative evaluation (e.g., recall\@K) but are also visualized in a grid format to support qualitative analysis. Each retrieval result consists of the query logo on the top or left, followed by the K most similar logos from the training set, ordered by their proximity in embedding space. This grid-based layout provides intuitive insight into how well the model has captured logo semantics, and whether it can retrieve conceptually coherent alternatives—e.g., logos with similar typography, shape, color palette, or symbolic elements.

From a deployment perspective, the retrieval pipeline is lightweight and efficient. Since the heavy lifting is done during training and embedding extraction, the inference phase is reduced to a single forward pass through the TripletNet followed by a nearest neighbor query in FAISS. This enables integration into interactive applications such as logo suggestion engines, duplicate detection systems, or brand monitoring platforms.

Importantly, the retrieval pipeline is designed to generalize beyond the training categories. Unlike traditional classification-based models that are restricted to fixed label sets, this embedding-based retrieval method can operate in an open-set setting, handling unseen logos and new branding styles without re-training. As such, it provides both flexibility and scalability—two essential properties for practical adoption in the dynamic and evolving landscape of visual identity systems.

In summary, the retrieval pipeline operationalizes the learned similarity space through an efficient and accurate nearest neighbor search mechanism. It bridges the gap between model training and real-world utility, offering a powerful tool for interactive and automated logo similarity search at scale.

---
"""

