# -*- coding: utf-8 -*-
"""Prompts-Embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Mahmood-Anaam/logo-similarity-retrieval/blob/main/notebooks/Prompts-Embedding.ipynb

# Prompts Embedding

## Imports
"""

!pip install -U sentence-transformers datasets --quiet

import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas()

import matplotlib.pyplot as plt
import seaborn as sns
import os
import torch
import transformers
import random
from sentence_transformers import SentenceTransformer

import warnings
warnings.filterwarnings('ignore')


images_dir = "/content/drive/MyDrive/Data/images_128x128_new.zip"
captions_path = "/content/drive/MyDrive/Data/logo_image_caption.tsv"
output_dir = "/content/drive/MyDrive/logo_recognition_similarity_search_project/output"
os.makedirs(output_dir, exist_ok=True)

"""## Data Exploration

### Laod dataset
"""

raw_df = pd.read_csv(captions_path, sep='\t')
raw_df.id = raw_df.id.apply(lambda x: str(x).strip().lower())
raw_df.head()

"""### Exploratory & Preprocessing"""

raw_df.info()

raw_df.describe(include='all').T

import re

def clean_text(text):
  """
    Cleans a given text by removing non-english characters. Converts text to lowercase.

    Args:
        text (str): The input text.

    Returns:
        str: The cleaned text. Returns an empty string if input is not a string.
    """

  if not isinstance(text, str):
    return ""
  text = re.sub(r'[^\x00-\x7F]+', ' ', text)
  text = text.lower()
  text = text.strip()

  return text

raw_df['prompt'] = raw_df['prompt'].progress_apply(clean_text)

raw_df.describe(include='all').T

raw_df.info()

raw_df.head()

"""## Prompts Embedding"""

from sentence_transformers import SentenceTransformer
import datasets
import torch

model_id = 'sentence-transformers/all-MiniLM-L6-v2'
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# convert raw_df to datasets
ds = datasets.Dataset.from_pandas(raw_df)
ds

# Load model from HuggingFace Hub
model = SentenceTransformer(model_id,device=device)

model

def batch_encode(examples):
  encoded_prompts = model.encode(examples["prompt"], show_progress_bar=False)
  return {'encoded_prompt': encoded_prompts}

encoded_prompts_ds = ds.map(
                            batch_encode,
                            batched=True,
                            batch_size=1000,
                            desc="Encoding prompts"
                            )

# Save the encoded dataset
encoded_prompts_ds.save_to_disk(os.path.join(output_dir, "encoded_prompts_dataset"))

encoded_prompts_ds

"""## Load Encoded Prompts Dataset"""

import datasets
import os

ds_path = os.path.join(output_dir, "encoded_prompts_dataset")

ds = datasets.load_from_disk(ds_path)
ds

print("Shape of the dataset: ", ds.shape)

print(ds[0])

len(ds[0]['encoded_prompt'])

# convert dataset to DataFrame
df = ds.to_pandas()
df.head()

df.info()

print("Shape of the dataset: ", df.shape)

"""

---

"""