# -*- coding: utf-8 -*-
"""Trainer_Resnet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Mahmood-Anaam/logo-similarity-retrieval/blob/main/notebooks/Trainer_Resnet50.ipynb

# Trainer Resnet50

## Import Libraries
"""

!pip install datasets==3.6.0 --no-warn-conflicts --quiet

import os
import json
from pathlib import Path
import datasets
import numpy as np
import random
import pandas as pd
from tqdm import tqdm
import logging
from google.colab import userdata

import torch
import torchvision
import huggingface_hub
from PIL import Image
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

"""## Configuration"""

import os
from pathlib import Path
import torch

class Config:
    """
    Configuration class for the Triplet Network training project.
    """

    # ========== Project Name & Paths ==========
    project_name = "logo_recognition_similarity_search_project"
    base_dir = Path("/content/drive/MyDrive") / project_name
    output_dir = base_dir / "output_last"
    cache_dir = base_dir / "cache"

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(cache_dir, exist_ok=True)

    # ========== Dataset Settings ==========
    dataset_path = "mlproject5606/Original-Logo-Recognition-Category-Split-Dataset"
    dataset_cache_dir = cache_dir / dataset_path.split("/")[-1]
    category_indices_cache_dir = cache_dir / "Category-Indices-last"
    train_category_indices_path = category_indices_cache_dir / "category_train_indices.json"
    test_category_indices_path = category_indices_cache_dir / "category_test_indices.json"
    val_category_indices_path = category_indices_cache_dir / "category_val_indices.json"

    # ========== Model Settings ==========
    backbone_type = "Resnet50"        # "Resnet50"
    output_dim = 512                  # Output dimension of backbone CNN
    embedding_dim = 256               # Final embedding dimension (after projection head)
    ff_block_units = [512, 256]       # Units in feed-forward projection head
    dropout = 0.3                     # Dropout rate in projection head
    freeze_backbone = True            # Whether to freeze CNN weights

    # ========== Training Runtime Settings ==========
    device = "cuda" if torch.cuda.is_available() else "cpu"
    seed = 42
    batch_size = 1024
    num_workers = 4

    # ========== Hugging Face TrainingArguments ==========
    num_train_epochs = 10
    learning_rate = 1e-4
    weight_decay = 0.01
    logging_steps = 5
    eval_strategy = "epoch"             # Options: "no", "steps", "epoch"
    save_strategy = "epoch"             # Options: "no", "steps", "epoch"
    save_total_limit = 2                # Keep only last N checkpoints
    metric_for_best_model = "eval_loss"
    greater_is_better = False
    report_to = "tensorboard"           # Enables TensorBoard logging
    model_id = f'mlproject5606/Logo-Recognition-{backbone_type}-TripletLoss'
    model_output_dir = output_dir / f'{model_id.split("/")[1]}'
    model_evaluation_dir = model_output_dir / "evaluation"
    os.makedirs(model_evaluation_dir, exist_ok=True)


# Create configuration object
cfg = Config()

"""## Load Dataset"""

ds = datasets.load_dataset(path = cfg.dataset_path,
                           cache_dir = cfg.dataset_cache_dir,
                           )

ds = ds.with_format('torch')
ds

"""## Triplet Dataset"""

import json
import random
import torch
import datasets


class TripletDataset(torch.utils.data.Dataset):
    """
    Custom dataset class for triplet network.
    """

    def __init__(self,
                 ds:datasets.Dataset,
                 category_indices_path:str,
                 seed:int=None,
                 ):
        """
        Initialize the TripletDataset.
        """
        print(f"[INFO] Initializing Triplet Dataset")

        self.ds = ds
        self.seed = seed
        self.rng = random.Random() if seed is None else random.Random(seed)
        self.category_indices_path = category_indices_path

        print(f"[INFO] Loading category indices from: {self.category_indices_path}")
        self.category_indices = self._load_category_indices(self.category_indices_path)
        self.categories = sorted(list(self.category_indices.keys()))

        print(f"[INFO] Triplet Dataset Initialized")



    def _load_category_indices(self, category_indices_path):
        """
        Load category indices from a JSON file.
        """
        with open(category_indices_path, "r") as f:
            category_indices = json.load(f)
        category_indices = {int(k): v for k, v in category_indices.items()}
        return category_indices

    def __len__(self):
        """
        Return the number of samples in the dataset.
        """
        return len(self.ds)


    def _get_positive(self, category, anchor_idx=None):
        """
        Get a positive item for the given anchor index and category.
        """
        positive_indices = self.category_indices[category]
        if len(positive_indices)<2:
            positive_idx = positive_indices[0]

        elif anchor_idx is None:
            positive_idx = self.rng.choice(positive_indices)

        else:
            positive_idx = anchor_idx
            while positive_idx==anchor_idx:
                positive_idx = self.rng.choice(positive_indices)

        return self.ds[positive_idx]


    def _get_negative(self, category):
        """
        Get a negative item for the given anchor category.
        """
        negative_category = category
        while negative_category==category:
            negative_category = self.rng.choice(self.categories)

        negative_indices = self.category_indices[negative_category]
        negative_idx = self.rng.choice(negative_indices)
        return self.ds[negative_idx]


    def __getitem__(self, idx):
        """
        Get a triplet sample from the dataset.
        """
        anchor_idx = idx
        anchor = self.ds[anchor_idx]
        category = int(anchor["category"])

        positive = self._get_positive(category=category,
                                      anchor_idx=anchor_idx
                                      )


        negative = self._get_negative(category=category)


        return anchor , positive , negative

    @staticmethod
    def display_sample(sample):
        """
        Display the anchor, positive, and negative images.
        """
        images = []
        for i in range(len(sample)):
            image = sample[i]["image"]
            if isinstance(image, Image.Image):
                image = np.array(image)
            elif isinstance(image, torch.Tensor):
                image = image.permute(1, 2, 0).numpy()
            images.append(image)

        fig, axes = plt.subplots(1, 3, figsize=(10, 5))
        axes[0].imshow(images[0])
        axes[0].set_title(f"Anchor cat({sample[0]['category']})")

        axes[1].imshow(images[1])
        axes[1].set_title(f"Positive cat({sample[1]['category']})")

        axes[2].imshow(images[2])
        axes[2].set_title(f"Negative cat({sample[2]['category']})")

        for ax in axes:
            ax.axis("off")
        plt.show()

    @staticmethod
    def collate_fn(batch):
        """
        Collate function to process triplet batch for HuggingFace Trainer.

        Args:
            batch: List of (anchor_dict, positive_dict, negative_dict)

        Returns:
            Dict with keys 'anchor', 'positive', 'negative', each containing image batch tensor
        """
        anchors, positives, negatives = zip(*batch)

        anchor_images = torch.stack([item["image"].float()/255.0 for item in anchors])
        positive_images = torch.stack([item["image"].float()/255.0 for item in positives])
        negative_images = torch.stack([item["image"].float()/255.0 for item in negatives])

        return {
            "anchor": anchor_images,
            "positive": positive_images,
            "negative": negative_images
        }

train_dataset = TripletDataset(ds=ds["train"],
                               category_indices_path=cfg.train_category_indices_path,
                               seed=None
                               )

print(f"[INFO] Number of samples in train_dataset: {len(train_dataset)}")

val_dataset = TripletDataset(ds=ds["validation"],
                             category_indices_path=cfg.val_category_indices_path,
                             seed=None
                             )

print(f"[INFO] Number of samples in val_dataset: {len(val_dataset)}")

"""## Models"""

from abc import ABC, abstractmethod
import torch
import torch.nn as nn
import torch.nn.functional as F
from huggingface_hub import PyTorchModelHubMixin
from transformers import Trainer, TrainingArguments,PretrainedConfig
import torchvision.models as models
from torchvision.models import ResNet50_Weights

"""### Base Backbone"""

from gc import freeze
class BaseBackbone(nn.Module, ABC):
    """
    Abstract base class for all CNN backbone models.
    Subclasses must implement the `forward` method.
    """

    def __init__(self, output_dim: int):
        """
        Args:
            output_dim (int): Dimension of the feature vector output by the backbone
        """
        super().__init__()
        self.output_dim = output_dim
        self.transforms = None

    def set_requires_grad(self, requires_grad: bool):
        """
        Set the requires_grad attribute of all parameters in the model.

        Args:
            requires_grad (bool): Whether to set the requires_grad attribute to True or False
        """
        for param in self.parameters():
            param.requires_grad = requires_grad

    def forward(self, x):
        """
        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, num_channels, height, width)

        Returns:
            torch.Tensor: Output tensor of shape (batch_size, output_dim)
        """
        raise NotImplementedError

"""### ResNet50"""

class ResNet50Backbone(BaseBackbone):
    """
    ResNet50 backbone with optional layer freezing.
    """
    def __init__(self, output_dim=2048, weights=ResNet50_Weights.IMAGENET1K_V2, freeze=True):
        super().__init__(output_dim)
        self.transforms = weights.transforms()
        self.model = models.resnet50(weights=weights)
        self.model.fc = torch.nn.Identity()
        if freeze:
            self.set_requires_grad(False)


    def forward(self, x):
        """
        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, num_channels, height, width)

        Returns:
            torch.Tensor: Output tensor of shape (batch_size, output_dim)
        """
        x = self.transforms(x)
        x = self.model(x)
        x = x.view(x.size(0), -1)
        return x

"""### Triplet Loss"""

class TripletLossTrainer(Trainer):
    """
    Custom HuggingFace Trainer for Triplet Loss.
    """

    def __init__(self, *args, margin: float = 1.0, reduction: str = "mean", **kwargs):
        super().__init__(*args, **kwargs)
        self.triplet_loss_fn = nn.TripletMarginLoss(margin=margin, p=2, reduction=reduction)

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        outputs = model(**inputs)
        loss = self.triplet_loss_fn(outputs["anchor"], outputs["positive"], outputs["negative"])
        return (loss, outputs) if return_outputs else loss

    def prediction_step(self, model, inputs, prediction_loss_only=False, ignore_keys=None):
        inputs = self._prepare_inputs(inputs)
        with torch.no_grad():
            outputs = model(**inputs)
            loss = self.triplet_loss_fn(outputs["anchor"], outputs["positive"], outputs["negative"])

        return (loss, None, None) if prediction_loss_only else (loss, outputs, None)

"""### TripletNet"""

class FeedForwardBlock(nn.Sequential):
    """
    Custom feed-forward block (Dense -> BN -> ReLU -> Dropout).
    """
    def __init__(self, in_features: int, out_features: int, dropout: float):
        super().__init__(
            nn.Linear(in_features, out_features),
            nn.BatchNorm1d(out_features),
            nn.ReLU(),
            nn.Dropout(dropout)
        )


class TripletNet(nn.Module, PyTorchModelHubMixin):
    """
    TripletNet with a CNN backbone and optional feed-forward projection blocks.

    Args:
        backbone (nn.Module): A frozen or trainable CNN backbone with .encode()
        embedding_dim (int): Final dimensionality of the embedding space
        ff_block_units (List[int]): List of hidden units in feed-forward blocks
        dropout (float): Dropout rate
    """

    _BACKBONES = {
        "Resnet50": ResNet50Backbone,
        }


    def __init__(self,
                 config: dict
                 ):
        super().__init__()
        self.config = config
        if config["backbone_type"] not in self._BACKBONES:
            raise ValueError(f"Unknown backbone type: {self.config['backbone_type']}")
        self.backbone = self._BACKBONES[self.config['backbone_type']]()



        # Construct projection head
        layers = []
        input_dim = self.backbone.output_dim
        for units in self.config['ff_block_units']:
            layers.append(FeedForwardBlock(input_dim, units, self.config['dropout']))
            input_dim = units

        layers.append(nn.Linear(input_dim, self.config['embedding_dim']))
        self.projection_head = nn.Sequential(*layers)
        self.config = PretrainedConfig(**self.config)





    def encode(self, x: torch.Tensor) -> torch.Tensor:
        features = self.backbone(x)
        projection = self.projection_head(features)
        return F.normalize(projection, p=2, dim=1)

    def forward(self,
                anchor: torch.Tensor,
                positive: torch.Tensor,
                negative: torch.Tensor) -> dict:
        return {
            "anchor": self.encode(anchor),
            "positive": self.encode(positive),
            "negative": self.encode(negative)
        }

    def get_transforms(self):
        return self.backbone.transforms

"""## Train"""

config = {
"backbone_type":cfg.backbone_type,
"embedding_dim":cfg.embedding_dim,
"ff_block_units":cfg.ff_block_units,
 "dropout": cfg.dropout
 }

model =TripletNet(config)
model.to(cfg.device)

training_args = TrainingArguments(
    output_dir=str(cfg.model_output_dir / "checkpoints"),
    logging_dir=str(cfg.model_output_dir / "logs"),
    per_device_train_batch_size=cfg.batch_size,
    per_device_eval_batch_size=cfg.batch_size,
    num_train_epochs=cfg.num_train_epochs,
    learning_rate=cfg.learning_rate,
    weight_decay=cfg.weight_decay,
    logging_steps=cfg.logging_steps,
    eval_strategy=cfg.eval_strategy,
    save_strategy=cfg.save_strategy,
    save_total_limit=cfg.save_total_limit,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to=cfg.report_to
)

trainer = TripletLossTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    margin=1.0,
    data_collator=TripletDataset.collate_fn,
)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir={cfg.model_output_dir}/logs

trainer.train()

model = TripletNet.from_pretrained(trainer.state.best_model_checkpoint,config=config)
model.save_pretrained(
    save_directory = cfg.model_output_dir / "final_model",
    repo_id = cfg.model_id,
    push_to_hub = True,
    token = userdata.get('HF_TOKEN')
)

"""## Visualize Loss Curves"""

from tensorboard.backend.event_processing import event_accumulator
import matplotlib.pyplot as plt
import os

event_file = max((cfg.model_output_dir / "logs").glob("events.*"), key=os.path.getmtime)
ea = event_accumulator.EventAccumulator(str(event_file))
ea.Reload()

tags = ["train/loss", "eval/loss"]
titles = ["Train Loss", "Validation Loss"]
color = "#1f77b4"

fig, axes = plt.subplots(1, 2, figsize=(14, 4.5))
axes = axes.flatten()
for i, tag in enumerate(tags):
    if tag in ea.Tags()["scalars"]:
        data = ea.Scalars(tag)
        steps = [e.step for e in data]
        values = [e.value for e in data]
        axes[i].plot(steps, values, color=color, linewidth=2)
        axes[i].set_title(titles[i], fontsize=14)
        axes[i].set_xlabel("Step", fontsize=12)
        axes[i].set_ylabel("Loss", fontsize=12)
        axes[i].grid(True, linestyle="--", alpha=0.6)

fig.suptitle(f"{cfg.backbone_type} TripletNet - Loss Curves", fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig(f"{cfg.model_evaluation_dir}/Loss_curves.png", dpi=300)
plt.show()

"""## Dataset Embedding"""

model=TripletNet.from_pretrained(cfg.model_id)
model.eval()
model.to(cfg.device)

torch.set_grad_enabled(False)

for split in ["train","validation","test"]:

    embedding_ds = ds[split].map(lambda batch: {"embedding":model.encode(batch['image'].to(cfg.device)).cpu().detach()},
                                 batched=True,
                                 batch_size=cfg.batch_size,
                                 desc=f"Generating embeddings for {split}"
                                 )

    embedding_ds.push_to_hub(f"{cfg.backbone_type}-TripletLoss-Embedding-Dataset",
                             split = split,
                             private = True,
                             token = userdata.get('HF_TOKEN')
                             )

"""## Disconnect"""

# Disconnect and delete the current runtime in Google Colab
from google.colab import runtime

runtime.unassign()

