
@startuml
skinparam style strict
skinparam shadowing false
skinparam rectangle {
  FontSize 12
  FontName "Arial"
  RoundCorner 10
  BackgroundColor White
}

skinparam defaultTextAlignment center
left to right direction
title Inference Phase: Logo Retrieval System

skinparam package {
  BackgroundColor #F9F9F9
  BorderColor Black
}


package "Inference Phase (Online Retrieval)" <<Inference>> {
  rectangle QueryLogo as "Query Logo Image"
  rectangle VisInfer as "ResNet50 Encoder\n2048-D"
  rectangle TripletNetInfer as "Trained TripletNet\n256-D Embedding"
  rectangle FaissIndex as "FAISS Index\nL2 Similarity Search"
  rectangle TopK as "Top-K Similar Logos"

  QueryLogo -down-> VisInfer
  VisInfer -down-> TripletNetInfer
  TripletNetInfer -down-> FaissIndex
  FaissIndex -down-> TopK
}
@enduml
